### PR TITLE
TCK for AWS Lambda Events Serialisation with serde and Jackson databind 

### LINKED ISSUE #1768: NPE Serializing Api Gateway V2 event with Serde
For a JSON 

```json
{
    "version": "2.0",
    "routeKey": "$default",
    "rawPath": "/",
    "rawQueryString": "",
    "headers": {
        "accept": "*/*",
        "content-length": "0",
        "host": "y9j2vzg784.execute-api.us-east-1.amazonaws.com",
        "user-agent": "curl/7.88.1",
        "x-amzn-trace-id": "Root=1-6488b8c4-28a476ca7ae7e1447b5e2d8f",
        "x-forwarded-for": "80.26.234.66",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https"
    },
    "requestContext": {
        "accountId": "646406757139",
        "apiId": "y9j2zvz764",
        "domainName": "y5j3zzg784.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "y5j3zzg784",
        "http": {
            "method": "GET",
            "path": "/",
            "protocol": "HTTP/1.1",
            "sourceIp": "80.26.234.66",
            "userAgent": "curl/7.88.1"
        },
        "requestId": "GeHOyjS9oAMEV-A=",
        "routeKey": "$default",
        "stage": "$default",
        "time": "13/Jun/2023:18:43:16 +0000",
        "timeEpoch": 1686681796799
    },
    "isBase64Encoded": false
}
```

We get: 

```
Cannot invoke "String.length()" because "this.input" is null: java.lang.NullPointerExceptionjava.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null	at java.base/java.net.URI$Parser.parse(Unknown Source)	at java.base/java.net.URI.<init>(Unknown Source)	at java.base/java.net.URI.create(Unknown Source)	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyServletRequest.<init>(ApiGatewayProxyServletRequest.java:59)	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:55)	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:35)	at io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:165)	at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:56)	at temp.TestHandler.handleRequest(TestHandler.java:23) | Cannot invoke "String.length()" because "this.input" is null: java.lang.NullPointerException java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null at java.base/java.net.URI$Parser.parse(Unknown Source) at java.base/java.net.URI.<init>(Unknown Source) at java.base/java.net.URI.create(Unknown Source) at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyServletRequest.<init>(ApiGatewayProxyServletRequest.java:59) at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:55) at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyEventHandler.createExchange(ApiGatewayProxyEventHandler.java:35) at io.micronaut.servlet.http.ServletHttpHandler.exchange(ServletHttpHandler.java:165) at io.micronaut.function.aws.proxy.payload1.ApiGatewayProxyRequestEventFunction.handleRequest(ApiGatewayProxyRequestEventFunction.java:56) at temp.TestHandler.handleRequest(TestHandler.java:23)
```

### PR DESCRIPTION
**Pull request by sdelamo**
Close #1768

[AWS Lambda Java Events](https://github.com/aws/aws-lambda-java-libs/tree/main/aws-lambda-java-events) does not provide any JSON Schema or nullability annotations in their classes to convey which fields are required and which are not. 

`test-suite-aws-lambda-events-serde/src/test/resources/apiGatewayV2HTTPEvent.json` included in this PR is real JSON obtained with a API Gateway HTTP with default Payload (v2). 

We have [`@SerdeImport` for the POJOs in AWS Lambda Events](https://github.com/micronaut-projects/micronaut-aws/blob/master/aws-lambda-events-serde/src/main/java/io/micronaut/aws/lambda/events/serde/APIGatewayV2HTTPEventSerde.java#L27-L33).

However, [Serde assumes that if you don't have a nullability annotation the field is required](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/APIGatewayV2HTTPEvent.java#L59).

**I think that it is wrong behaviour in Serde**. Serde should consider fields not annotated as `@Nullable`. Which is the default in Java. Things can be null by default. 

I included a Disabled test int this PR  which uses serde which shows the issue. 
`test-suite-aws-lambda-events-serde/src/test/java/io/micronaut/aws/lambda/events/ApiGatewayV2EventTest.java`

Please, note that test passes with jackson-databind. 

To workaround, this PR creates a module `micronaut-aws-lambda-events` which ports the HTTP Trigger events and adds the Nullability annotations (this should help with serialisation and kotlin integration), `Serdeable` annotations directly and it removes Lombok.

Since there are no documentation about what is required or not. I have played it safe and annotated everything with `@Nullable`. 

AWS Lambda Java Events are Apache 2.0 licensed. 

|AWS Lambda Events | Micronaut AWS Lambda Events | 
|:--- |:---- |
| `com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent` |  `io.micronaut.aws.lambda.events.APIGatewayProxyRequestEvent` |
| `com.amazonaws.services.lambda.runtime.events APIGatewayProxyResponseEvent.` |  `io.micronaut.aws.lambda.events. APIGatewayProxyResponseEvent ` |
| `com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent` |  `io.micronaut.aws.lambda.events.APIGatewayV2HTTPEvent` |
| `com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse` |  `io.micronaut.aws.lambda.events.APIGatewayV2HTTPResponse` |
| `com.amazonaws.services.lambda.runtime.events.ApplicationLoadBalancerRequestEvent` |  `io.micronaut.aws.lambda.events.ApplicationLoadBalancerRequestEvent` |
| `com.amazonaws.services.lambda.runtime.events.ApplicationLoadBalancerResponseEvent` |  `io.micronaut.aws.lambda.events.ApplicationLoadBalancerResponseEvent` |

With this PR, users writing Lambda applications with controllers would not need to add AWS Lambda Java Events to their classpath. 

We can either: 

- Merge this PR
- Tell users serde serialisation does not support Lambda for certain events
- Change how serde behaves

### CODE REVIEW

File: test-suite-aws-lambda-events-serde/src/test/java/io/micronaut/aws/lambda/events/ApiGatewayV2EventTest.java [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+import org.junit.jupiter.api.Test;
+import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent;
+import java.io.File;
+import java.io.IOException;
+
+import static org.junit.jupiter.api.Assertions.*;
+
+class ApiGatewayV2EventTest {
+
+    @Disabled("Unexpected exception thrown: io.micronaut.function.aws.CustomPojoSerializerException: io.micronaut.serde.exceptions.SerdeException: Unable to deserialize type [RequestContext requestContext]: Null argument specified for [authorizer]. If this argument is allowed to be null annotate it with @Nullable")
```
Comment (timyates) [inline test-suite-aws-lambda-events-serde/src/test/java/io/micronaut/aws/lambda/events/ApiGatewayV2EventTest.java:14]: I miss `PendingFeature` in Spock 😔

**Review by timyates — APPROVED** [review]
Maybe a `defaultToNullable` could be added to `SerdeImport` to add nullable annotation to the bean definition if Nullability annotations are missing?

But I took a brief look, and it seems non-trivial...  And there's such a proliferation of Nullability annotations, it would be hard to encompass all

**Comment by sdelamo** [comment]
@timyates with the changes of serde to be not strict with nullables by default and have the ability to configure we can use both serde or Jackson databind to serialise API Gateway V2 events. 

Can you please re-review this PR?

**Review by timyates — APPROVED** [review]
